### PR TITLE
feat(ClassInfo): display cancellation text if present

### PR DESCRIPTION
**Pull request by AdrianAndersen**
Screenshot 2024-02-11 at 15 16 30

Depends on https://github.com/mathiazom/rezervo/pull/40

### CODE REVIEW

**Comment by mathiazom** [comment]
How about using an [Alert](https://mui.com/material-ui/react-alert/#titles) with description from the API?

**Comment by AdrianAndersen** [comment]
Screenshot 2024-02-11 at 15 57 33
Screenshot 2024-02-11 at 15 57 14

**Comment by AdrianAndersen** [comment]
Hmm, not sure I like the alert when there is no description. Could do a hybrid approach having an Alert if there is a description and just the text as previously otherwise. What do you think?

**Comment by mathiazom** [comment]
> Hmm, not sure I like the alert when there is no description. Could do a hybrid approach having an Alert if there is a description and just the text as previously otherwise, but I think just the parenthesis look fine too. What do you think?

Yea, that component is missing a title-only variant :roll_eyes: 

What about having the title variant if there is a description, and use the non-title variant when we only have the generic cancellation text.

Screenshot from 2024-02-11 20-37-06
Screenshot from 2024-02-11 20-37-36

**Comment by AdrianAndersen** [comment]
> What about having the title variant if there is a description, and use the non-title variant when we only have the generic cancellation text.

Sure, that looks good 👍🏻 
Implemented in https://github.com/mathiazom/rezervo-web/pull/107/commits/cf87d9351d00eb01b379da8892d72a34e0150255

**Review by mathiazom — APPROVED** [review]
:sunglasses:

**Pull request merged**
