### PR TITLE
build(pwa): migrate to serwist

### PR DESCRIPTION
**Pull request by AdrianAndersen**
Please refer to the official post by the maintainer: [Introducing Serwist](https://github.com/DuCanhGH/next-pwa/discussions/121)

### CODE REVIEW

**Comment by AdrianAndersen** [comment]
It feels like the maintainer dude changes the package composition and installation guidance for every major version. Updated to the way he does it in the V9 docs now tho, hopefully he keeps it this way for a while 👀

**Comment by AdrianAndersen** [comment]
I figured I would put in another 🥕 in this PR, so I bumped most of our minor versions as well. This includes next js, which actually reduces the overall bundle size by quite a few kilobytes. All of these should be totally non-breaking bumps, mostly bug fixes on the part of the packages.

**Comment by AdrianAndersen** [comment]
## Before and after

Screenshot 2024-04-24 at 00 59 04
Screenshot 2024-04-24 at 00 59 07

**Comment by mathiazom** [comment]
> should be totally non-breaking bumps

Yes, they should... but the `next` bump is actually a little risky (see https://github.com/mathiazom/rezervo-web/commit/9163ce48d69d489024fd9a9fdb748770aaae9e6e). Luckily they seem to have fixed the regression in 14.2.0. 

So the :carrot: could have made it more difficult to merge :upside_down_face:

**Review by mathiazom — APPROVED** [review]

**Pull request merged**
